SELECT EMPNO, NAME, HIREDATE, SYSDATE,
  MONTH_BETWEEN(HIREDATE, SYSDATE) AS MONTH1,
  MONTH_BETWEEN(SYSDATE, HIREDATE) AS MONTH2
	FROM EMP;

SELECT SYSDATE, 
  NEXT_DAY(SYSDATE, ‘월요일’), LAST_DAY(SYSDATE)
  FROM DUAL;

SELECT SYSDATE,
ROUND(SYSDATE, ‘CC’) AS CC, ROUND(SYSDATE, ‘YYYY’) AS YYYY,
ROUND(SYSDATE, ‘Q’) AS Q, ROUND(SYSDATE, ‘DDD’) AS DDD,
ROUND(SYSDATE, ‘HH’) AS HH
FROM DUAL;
SELECT SYSDATE,
TRUNC(SYSDATE, ‘CC’) AS CC, TRUNC(SYSDATE, ‘YYYY’) AS YYYY,
TRUNC(SYSDATE, ‘Q’) AS Q, TRUNC(SYSDATE, ‘DDD’) AS DDD,
TRUNC(SYSDATE, ‘HH’) AS HH
FROM DUAL;

SELECT TO_CHAR(SYSDATE, ‘YYYY/MM/DD HH24:MI:SS’) AS NOW
FROM DUAL;
 
SELECT SYSDATE,
  TO_CHAR(SYSDATE, ‘MM’) AS MM,
  TO_CHAR(SYSDATE, ‘MON’) AS MON,
  TO_CHAR(SYSDATE, ‘DD’) AS DD,
  TO_CHAR(SYSDATE, ‘DY’) AS DY,
  TO_CHAR(SYSDATE, ‘DAY’) AS DAY
  FROM DUAL;

SELECT TO_DATE(‘20210101’, ‘YYYY/MM/DD’) AS TODATE FROM DUAL;
SELECT TO_CHAR(TO_DATE('2021-01-01', 'YYYY/MM/DD'), 'YYYY-MM-DD') AS TODATE FROM DUAL;

SELECT TO_NUMBER(‘1,300’, ‘999,999’) AS NUM FROM DUAL;

SELECT EMPNO, ENAME, COMM, NVL(COMM, 0), SAL+NVL(COMM, 0) FROM EMP;

SELECT EMPNO, ENAME, COMM, NVL2(COMM, ‘X’, 0) FROM EMP;

SELECT EMPNO, ENAME, JOB, SAL,
  DECODE(JOB, 
    ‘MANAGE’, SAL*1.1,
    ‘SALESMAN’, SAL*1.05,
    ‘ANALYST’, SAL,
    SAL*1.03) AS UPSAL
FROM EMP;

SELECT EMPNO, ENAME, JOB, SAL,
  CASE JOB
    WHEN ‘MANAGE’ THEN SAL*1.1
    WHEN ‘SALESMAN’ THEN SAL*1.05
    WHEN ‘ANALYST’ THEN SAL
    ELSE SAL*1.03 
    END AS UPSAL
  FROM EMP;
  SELECT EMPNO, ENAME, COMM,
    CASE 
      WHEN COMM IS NULL THEN ‘해당사항 없음’
      WHEN COMM = 0 THEN ‘수당없음’
      WHEN COMM > 0 THEN ‘수당 : ‘ || COMM
      END AS COMM_RESULT
    FROM EMP;

SELECT COUNT(*), COUNT(SAL), COUNT(DISTINCT SAL), COUNT(ALL SAL) FROM EMP;

SELECT SUM(COMM), SUM(SAL), SUM(DISTINCT SAL), SUM(ALL SAL) FROM EMP;

SELECT MAX(SAL), MIN(SAL) FROM EMP;

SELECT AVG(SAL) FROM EMP WHERE DEPTNO = 30;
SELECT AVG(DISTINCT SAL) FROM EMP WHERE DEPTNO = 30;

SELECT AVG(SAL), DEPTNO
FROM EMP
GROUP BY DEPTNO;

SELECT DEPTNO, JOB, AVG(SAL)
FROM EMP
GROUP BY DEPTNO, JOB
ORDER BY DEPTNO, JOB;

